# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development

In [1]:
pip install earthpy rasterio

DEPRECATION: Loading egg at /opt/conda/lib/python3.11/site-packages/tflite_model_maker-0.3.4-py3.11.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 24.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.7/27.7 MB 59.7 MB/s eta 0:00:00:00:01
Note: you may need to restart the kernel to use updated packages.


# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [3]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [38]:
arr1 = np.ones((10), dtype="int8")
print(arr1)

arr2 = np.arange(1, 21, 1, dtype="int")
print(arr2)

arr3 = np.ones((5, 5), dtype = "int")
print(arr3)

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [36]:
array4 = np.random.randn(3, 3, 3)
print(array4)

arr5 = array4.reshape(27,)
print(arr5)

[[[-0.16574905  0.22664707  0.61811484]
  [ 0.40055971 -0.31920997  2.6764015 ]
  [-0.40991537 -1.55471433  0.3682591 ]]

 [[ 1.54601662  1.44643491 -0.61303288]
  [-0.27787959 -1.87292489  0.4001524 ]
  [ 0.52870749 -0.15817939 -0.8204133 ]]

 [[-0.16894361  0.10859301 -0.80949168]
  [-1.17287902 -0.11892017  0.88405743]
  [ 0.51065177 -0.81408299  1.56037925]]]
[-0.16574905  0.22664707  0.61811484  0.40055971 -0.31920997  2.6764015
 -0.40991537 -1.55471433  0.3682591   1.54601662  1.44643491 -0.61303288
 -0.27787959 -1.87292489  0.4001524   0.52870749 -0.15817939 -0.8204133
 -0.16894361  0.10859301 -0.80949168 -1.17287902 -0.11892017  0.88405743
  0.51065177 -0.81408299  1.56037925]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [41]:
arr6 = np.linspace(1, 10, 20) 
print(arr6)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [8]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20 

In [14]:
print(a[3,4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [19]:
print(a[1:, 3:])


[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [25]:
print(list(a[1,:5]))

[6, 7, 8, 9, 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [26]:
a.sum()

325

## 2.6 

Calculate the sum of each row in `a`.

In [31]:
np.sum(a, axis=1) #Axis 1 is for row values; Axis 0 would be for column values 

array([ 15,  40,  65,  90, 115])

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [40]:
m = np.mean(a) 
print(m)
print('') 

mask = a > m  

print(mask)
print('')
print(a[mask])




13.0

[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [41]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [49]:
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

df = pd.read_csv(url, sep=",", header=0, encoding="ISO-8859-1")
df.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [53]:
print(df.shape) #rows=1430 and columns=4.  

(1430, 4)


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [70]:
print(df["co2_emmission"].mean())

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

ANSWER (after running code): maximum co2_emmision = 1712kg of CO2 and it belongs to Argentina, with Beef listed as food type. 

In [81]:
z = df["co2_emmission"].max()

max_z = df[df["co2_emmission"] == z]
print(max_z)

     country food_category  consumption  co2_emmission
2  Argentina          Beef        55.48         1712.0
1


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

Answer: 5 countries produce more than 1000kg CO2/person/year for at least one food type. 

In [91]:
highco2 = df[df["co2_emmission"] > 1000]

print(highco2)
print('')
print(len(highco2)) 

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

5


## 2.14

Which country consumes the least amount of beef per person per year?

ANSWER: Liberia consumes the least amount of beef per person at 0.78kg per person per year. 


In [109]:
b = df[df["food_category"] == "Beef"]

least_b = b.consumption.min()
print(least_b)

b_country = b[b["consumption"] == least_b]
print(b_country)


0.7799999999999999
      country food_category  consumption  co2_emmission
1410  Liberia          Beef         0.78          24.07


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

ANSWER: 74441.13kg per person per year is total emmisions for all meats. 

In [123]:
meats = ["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"]
df_meats = df[df["food_category"].isin(meats)] #.isin() is used when we have mutiple categories as apposed to == 

meat_emms = df_meats["co2_emmission"].sum()
print(meat_emms)

74441.13


# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

ANSWER: total of non-meat products is 30975.989999999998kg co2 per person per year. 

In [136]:
unq = df["food_category"].unique()
print(unq) 

non_m = ['Eggs', 'Milk - inc. cheese', 'Wheat and Wheat Products', 'Rice', 'Soybeans', 'Nuts inc. Peanut Butter'
 'Wheat and Wheat Products' 'Rice' 'Soybeans' 'Nuts inc. Peanut Butter']
print(non_m)

df_nonm = df[df["food_category"].isin(non_m)] 


nonm_emm = df_nonm["co2_emmission"].sum()
print('')
print("Answer:")
print(nonm_emm)

['Pork' 'Poultry' 'Beef' 'Lamb & Goat' 'Fish' 'Eggs' 'Milk - inc. cheese'
 'Wheat and Wheat Products' 'Rice' 'Soybeans' 'Nuts inc. Peanut Butter']
['Eggs', 'Milk - inc. cheese', 'Wheat and Wheat Products', 'Rice', 'Soybeans', 'Nuts inc. Peanut ButterWheat and Wheat ProductsRiceSoybeansNuts inc. Peanut Butter']

Answer:
30975.989999999998


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.